### ISSUE TITLE
Create a Delta from JSON file

### ISSUE THREAD

**Issue by agustin-giacchello** [OmarMuscatello/SimplePatch#11]
Hello, hope you are doing great and thanks for the library!

So, we are adding some unit test and we are trying to deserialize a Delta from a JSON file. The problem is that when we try to deserialize that file into a Delta using Newtonsoft, we get an empty Delta. The file is not deserializing ok, do you know why this is happening?

Thanks!

**Comment by OmarMuscatello** [comment]
Hello @agustin-giacchello and sorry for delay.

Unfortunally, I'm not able to reproduce the problem you reported.

I created this simple example which works fine for me:

```
class Person
{
    public string Name { get; set; }
}

static void Main(string[] args)
{
    DeltaConfig.Init(x =>
    {
        x.AddEntity<Person>();
    });

    var json = @"{""Name"": ""Omar""}";

    var delta = JsonConvert.DeserializeObject<Delta<Person>>(json);

    var newPerson = new Person();
    delta.Patch(newPerson);

    Console.WriteLine(newPerson.Name);
    Console.ReadKey();
}
```
If it doesn't help, could you please share your code so I can better understand?

Thank you

**Comment by agustin-giacchello** [comment]
Thanks you for your answer Omar, anyways we had to change the approach for partial update due to this [issue](https://github.com/OmarMuscatello/SimplePatch/issues/7). 

Thank you.
