### ISSUE TITLE
I don't see the link to update Person

### ISSUE THREAD

**Issue by Pankwood** [OmarMuscatello/SimplePatch#2]
https://github.com/OmarMuscatello/SimplePatch/blob/7977ca993f6e1d57b1529e5d0536c0d1b827ed27/examples/SimplePatch.Examples.Core/SimplePatch.Examples.Core.WebAPI/Controllers/ValuesController.cs#L56

**Comment by OmarMuscatello** [comment]
Thank you @Pankwood for your interest on SimplePatch.

Could you please better explain what the problem is or what do you expect to see?

Thank you

**Comment by Pankwood** [comment]
After line 56, I think you should have some like that:

person.Name = person.Name;

I can be wrong btw.

Best

**Comment by OmarMuscatello** [comment]
Do you mean
`personToPatch.Name = person.Name` ?

It's not required. The line (51) `person.Patch(personToPatch);` does all the magic for you.

**Comment by Pankwood** [comment]
I got it! Thanks!
