### ISSUE TITLE
Example jquery ajax patch

### ISSUE THREAD

**Issue by barry-schneider** [OmarMuscatello/SimplePatch#3]
I am having problems formating the jquery ajax patch call. Would you please provide an example?

        updateItem: function (item) {
                        var patch = { id: item.locationId, item};
                        return $.ajax({
                            type: "Patch",
                            url: "/api/jsgrid/location",
                            data: JSON.stringify(patch),
                            dataType: "json",
                            contentType: 'application/json; charset=utf-8'
                        });
                    }

The payload looks like this:

   {"id":3307,"item":{"locationName":"Dunkin' Donuts","address":"1 W Hampton St, Pemberton, NJ 08068, USA","locationId":3307,"isActive":false,"placeId":"ChIJDS6V69JAwYkR-79vLXLz6ZE"}}

**Comment by OmarMuscatello** [comment]
Thank you @barry-schneider for your interest on SimplePatch.
You shouldn't separate your id from your object.
You can
- add the `id` property to your `item` object

OR

- use the `id` property in the request URL.

**Adding `id` property to `item` object**
```
  updateItem: function(item) {
      item.id = item.locationId;
      return $.ajax({
          type: "Patch",
          url: "/api/jsgrid/location",
          data: JSON.stringify(item),
          dataType: "json",
          contentType: 'application/json; charset=utf-8'
      });
  }
```
Remember that you have to call the `IgnoreLetterCase` function in your configuration options if your to-patch entity uses Pascal Case for properties names.

**Using `id` property in the request URL**
```
updateItem: function(item) {
    return $.ajax({
        type: "Patch",
        url: "/api/jsgrid/location/" + item.locationId,
        data: JSON.stringify(item),
        dataType: "json",
        contentType: 'application/json; charset=utf-8'
    });
}
```
This solution requires that your action method support the `id` parameter in your route. Please, see *examples* folder of the repo to see how to achive that.
