### ISSUE TITLE
How would you go about model validation?

### ISSUE THREAD

**Issue by Thwaitesy** [OmarMuscatello/SimplePatch#5]
Hi @OmarMuscatello,

Great little library 👍

So, I'm trying to figure out the best way to handle validation of these patch requests. Basically, I have a standard poco object that requires some validation of some of the properties. e.g. Email needs to be an email and age needs to be greater than 18 etc..

Currently, validation gets handled with ModelState.IsValid() and Data Annotations, but because the model can be somewhat partial this validation isn't going to work as desired because it expects all properties to be bound when it does the validation.

One thought was to use something like https://fluentvalidation.net/ but again, it needs to have some override to say "Only when property is bound or passed up" then validate...

Do you have any thoughts or suggestions around validation of patch requests.

Cheers,
Sam

**Comment by OmarMuscatello** [comment]
Thank you @Thwaitesy for reporting this. Please, give me some days.

**Comment by OmarMuscatello** [comment]
A possible approach could be the following:
```
public static class DeltaExtensionsMethods
{
    public static IEnumerable<ValidationResult> Validate<TEntity>(this Delta<TEntity> delta) where TEntity : class, new()
    {
        var person = delta.GetEntity();

        var context = new ValidationContext(person);
        var results = new List<ValidationResult>();

        var typeTEntity = typeof(TEntity);

        foreach (var prop in delta)
        {
            context.MemberName = prop.Key;
            Validator.TryValidateProperty(typeTEntity.GetProperty(prop.Key).GetValue(person), context, results);
        }

        return results;
    }
}

public class Person
{
    [Required]
    public string Name { get; set; }

    public string Surname { get; set; }

    [Range(10, 20)]
    public int Age { get; set; }
}

public class HomeController : ApiController
{
    [HttpPatch]
    public IHttpActionResult Index(Delta<Person> deltaPerson)
    {
        var errors = deltaPerson.Validate();
        return Ok(errors);
    }
}
```
However, it has the following problems:
- executes validation for [excluded properties](https://github.com/OmarMuscatello/SimplePatch#--exclude-properties);
- can't [ignore null value for specified properties](https://github.com/OmarMuscatello/SimplePatch#--ignore-null-value).

Using [FluentValidation](https://fluentvalidation.net/) (with same problems of the above solution):
```
public static class DeltaExtensionsMethods
{
    public static FluentValidation.Results.ValidationResult ValidatePerson<TEntity>(this Delta<TEntity> delta) where TEntity : class, new()
    {
        var entity = delta.GetEntity();

        var context = new ValidationContext<TEntity>(entity, new PropertyChain(), new MemberNameValidatorSelector(delta.Select(x => x.Key)));

        IValidator v = new PersonValidator(); // This validator should be obtained based on TEntity. See https://stackoverflow.com/a/29727698/7772490.

        return v.Validate(context);
    }
}

public class Person
{
    [Required]
    public string Name { get; set; }

    public string Surname { get; set; }

    [Range(10, 20)]
    public int Age { get; set; }
}

public class PersonValidator : AbstractValidator<Person>
{
    public PersonValidator()
    {
        RuleFor(x => x.Name).NotEmpty();
        RuleFor(x => x.Age).InclusiveBetween(10, 20);
    }
}

public class HomeController : ApiController
{
    [HttpPatch]
    public IHttpActionResult Index(Delta<Person> deltaPerson)
    {
        var errors = deltaPerson.ValidatePerson();
        return Ok(errors);
    }
}
```
The best approach, of course, would be to integrate the `Validate` method as part of the library (in order to solve problems that above solutions have), which I'll do ASAP.

Hope it helps.

**Comment by Thwaitesy** [comment]
Cheers for that. I pushed forward on this, for our project we dont give any special meaning to nulls, so we made all our update contracts have nullable properties. Because of this, we are able to use fluent validation and the "When" clause..

I wrote an extension which made it a bit easier. It checks that the property is bound (or is not null) and then validates the rules.

```
public static class ValidationExtensions
{
    public static void WhenBound<TValue, TProperty>(this AbstractValidator<TValue> validator,
        Expression<Func<TValue, TProperty>> propertyExpression,
        Action<IRuleBuilderInitial<TValue, TProperty>> rules)
    {
        validator.When((value) => value != null, () => rules(validator.RuleFor(propertyExpression)));
    }
}
```

Use it like this:

```
public class UpdateUserRequest
{
    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}

public class Validator : AbstractValidator<UpdateUserRequest>
{
    public Validator()
    {
        this.WhenBound(x => x.Email, x => x.EmailAddress());
    }
}
```
