### ISSUE TITLE
In derived class can't patch properties from base class

### ISSUE THREAD

**Issue by schernev** [OmarMuscatello/SimplePatch#6]
Hi,
thank you for creating this great library.

I will try to explain the issue found:
I have the class MyViewModel, which derives MyViewModelBase.
For example:

```
public class MyViewModelBase
{
    public string Name { get; set; }
}
public class MyViewModel : MyViewModelBase
{
}
```

The configuration is:
`DeltaConfig.Init(x => x.AddEntity<MyViewModel >()`

The patch json is:
```
{
  "Name": "Test name"
}
```

In controller:

```
public IHttpActionResult Patch(int id, [FromBody] Delta<MyViewModel> delta)
{
...
}
```

In delta object in controller there is no "Name" property. If I register and use base class or override the Name property in derived class, it is there.

**Comment by OmarMuscatello** [comment]
Hello @schernev, thank you for reporting that. I'm working on a solution. I'll let you know as soon as the fix is published.

**Comment by OmarMuscatello** [comment]
Hello @schernev, please check the new version (v3.0.1) of SimplePatch which add support for child class patch. 

Please let me know if I solved your problem.
